---
- name: Copy OS images to IOS devices
  hosts: ios
  strategy: free
  gather_facts: no

  tasks:
    - name: Gather facts
      ios_facts:
        gather_subset: hardware

    - name: Copy files using SCP
      block:
        - name: Enabling SCP server
          ios_config:
            lines:
            - ip scp server enable
          register: scp_config
        
        - name: Disabling remote timeout
          ios_config:
            backup: yes
            parents: line vty 0 15
            lines:
            - exec-timeout 0 0
          register: timeout_config

        - name: Copy OS bundle to device
          include_role:
            name: copy_scp
          vars:
            bundle: 16.12.04

      always:
        - name: Restoring timeout config
          ios_config:
            src: "{{ timeout_config.backup_path }}"
          when: timeout_config.changed

        - name: Restoring scp config
          ios_config:
            lines:
            - no ip scp server enable
          when: scp_config.changed