#simple IOS config in ansible
---
- name: Sample IOS ping for Ansible 2.5
  hosts: iosxe
  gather_facts: no

  vars_prompt:
   - name: "dest_ip"
     prompt: "what's the destination IP address"
     # 10.10.20.48
     private: no

  tasks:
  - name: ping
    ios_ping:
      count: 5
      dest: "{{ dest_ip }}"


