#simple IOS config in ansible
---
- name: Sample IOS copy file from TFTP
  hosts: iosxe
  vars:
    new_ios_bin: "test_os.bin"
    new_ios_md5: "d41d8cd98f00b204e9800998ecf8427e"
    tftp_server: "192.168.255.1"
  gather_facts: no

  tasks:

  - name: CONFIGURING QUIET FILE PROMPT
    ios_config: 
      lines:
      - file prompt quiet
    vars:
      ansible_command_timeout: 300

  - name: COPYING {{ new_ios_bin }} on BOOTFLASH
    ios_command:
      commands:
      - copy tftp://{{ tftp_server }}/{{ new_ios_bin }} bootflash:{{ new_ios_bin }} vrf Mgmt-intf
    vars:
      ansible_command_timeout: 300

  - name: CHECK MD5 HASH
    ios_command:
      commands:
      - verify /md5 bootflash:{{ new_ios_bin }}
      wait_for:
      - result[0] contains {{ new_ios_md5 }}
      retries: 1
    vars:
      ansible_command_timeout: 300

  - name: UNCONFIGURING QUIET FILE PROMPT
    ios_config: 
      lines:
      - no file prompt quiet
    vars:
      ansible_command_timeout: 300