#simple IOS config in ansible
---
- name: Sample IOS copy file from TFTP
  hosts: iosxe
  vars:
    new_ios_bin: "test_os.bin"
    new_ios_md5: "d41d8cd98f00b204e9800998ecf8427e"
  gather_facts: no

  tasks:
  - name: COPYING {{ new_ios_bin }} on BOOTFLASH
    cisco.ios.ios_command:
      commands:
      - command: 'copy tftp://172.16.2.14/{{ new_ios_bin }} bootflash:'
        prompt: '[{{ new_ios_bin }}]'
        answer: "\r"
    vars:
      ansible_command_timeout: 1800

  - name: CHECK MD5 HASH
    cisco.ios.ios_command:
        commands:
        - command: "verify /md5 bootflash:{{ new_ios_bin }}"
    register: md5_result
    vars:
      ansible_command_timeout: 300

#  - debug:
#      msg: md5_result == {{ md5_result }}