#simple IOS config in ansible
---
- name: Copy IOS XE 16.12.4 files on the router.
  hosts: iosxe
  vars:
    folder_name: "TestAnsible"
    new_ios_bin_1: "test_os.bin"
    new_ios_bin_2: "test_os2.bin"
    new_ios_md5_1: "d41d8cd98f00b204e9800998ecf8427e"
    new_ios_md5_2: "d41d8cd98f00b204e9800998ecf8427e"
    tftp_server: "192.168.255.1"
  gather_facts: no

  tasks:

  - name: CONFIGURING QUIET FILE PROMPT
    ios_config: 
      lines:
      - file prompt quiet
    vars:
      ansible_command_timeout: 300

  - name: CREATING FOLDER {{ folder_name }}
    file:
      path: bootflash:{{ folder_name }}
      state: directory

  - name: COPYING {{ new_ios_bin_1 }} on BOOTFLASH
    ios_command:
      commands:
      - copy tftp://{{ tftp_server }}/{{ new_ios_bin_1 }} bootflash:{{ folder_name }}/{{ new_ios_bin_1 }} vrf Mgmt-intf
    vars:
      ansible_command_timeout: 300

  - name: CHECK MD5 HASH
    ios_command:
      commands:
      - verify /md5 bootflash:{{ folder_name }}/{{ new_ios_bin_1 }}
      wait_for:
      - result[0] contains {{ new_ios_md5_1 }}
      retries: 1
    vars:
      ansible_command_timeout: 300

  - name: COPYING {{ new_ios_bin_2 }} on BOOTFLASH
    ios_command:
      commands:
      - copy tftp://{{ tftp_server }}/{{ new_ios_bin_2 }} bootflash:{{ folder_name }}/{{ new_ios_bin_2 }} vrf Mgmt-intf
    vars:
      ansible_command_timeout: 300

  - name: CHECK MD5 HASH
    ios_command:
      commands:
      - verify /md5 bootflash:{{ folder_name }}/{{ new_ios_bin_2 }}
      wait_for:
      - result[0] contains {{ new_ios_md5_2 }}
      retries: 1
    vars:
      ansible_command_timeout: 300

  - name: UNCONFIGURING QUIET FILE PROMPT
    ios_config: 
      lines:
      - no file prompt quiet
    vars:
      ansible_command_timeout: 300