---
- name: Checking for free space
  fail:
    msg: The device does not have enough free space
  when: ansible_net_filesystems_info['bootflash:']['spacefree_kb'] < versions[version].total_size

- name: Enabling SCP server
  ios_config:
    lines:
    - ip scp server enable
  register: scp

- name: Creating required directories
  ios_directory:
    directories:
    - bootflash:/{{ remote_image_directory }}
    - bootflash:/{{ remote_image_directory }}/{{ version }}
  register: result

- name: Checking if files exist
  ios_file:
    list_files:
      directory: bootflash:/{{ remote_image_directory }}/{{ version }}
      get_md5: True
  register: file_md5

- name: Copying images
  loop: "{{  versions[version].images  }}"
  when: item.name not in file_md5['files'] or item.md5_hash != file_md5['files'][item.name]
  net_put:
    src: "{{  local_image_directory  }}/{{ version }}/{{ item.filename }}"
    dest: bootflash:/{{  remote_image_directory  }}/{{ version }}/{{ item.name }}
  vars:
    ansible_command_timeout: 3500 # 50 minutes

- name: Checking remote files
  loop: "{{  versions[version].images  }}"
  ios_file:
    verify:
      file: bootflash:{{  remote_image_directory  }}/{{ version }}/{{ item.filename }}
      expected_md5: "{{ item.md5_hash }}"

# TODO use task blocks to disable SCP even if a failure occured
- name: Disabling SCP server
  ios_config:
    lines:
    - no ip scp server enable
  when: scp.changed